name: Kedi Mod Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Make Gradle Executable
        run: chmod +x gradlew

      # 'build' yerine 'remapJar' diyoruz ki boş jar üretmesin
      - name: Build with Gradle
        run: ./gradlew clean remapJar --no-daemon

      - name: Upload Mod Jar
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: KediMod-Final-Build
          # Sadece remap edilmiş (dolu olan) dosyayı al
          path: build/libs/u-ma-1.0.0.jar
